category_concepts_dict = {}

#from https://en.wikipedia.org/w/index.php?title=Outline_of_physics&oldid=994270982

#category_concepts_dict['physics'] = ["Newton's", 'laws', 'of', 'motion', 'Lagrangian', 'mechanics', 'Hamiltonian', 'mechanics', 'kinematics', 'statics', 'dynamics', 'chaos', 'theory', 'acoustics', 'fluid', 'dynamics', 'continuum', 'mechanics', 'Electrostatics', 'electrodynamics', 'electricity', 'magnetism', "Maxwell's", 'equations', 'opticsDensity', 'dimension', 'gravity', 'space', 'time', 'motion', 'length', 'position', 'velocity', 'acceleration', 'mass', 'momentum', 'force', 'energy', 'angular', 'momentum', 'torque', 'conservation', 'law', 'harmonic', 'oscillator', 'wave', 'work', 'powerCapacitance', 'electric', 'charge', 'electric', 'current', 'electrical', 'conductivity', 'electric', 'field', 'electric', 'permittivity', 'electrical', 'resistance', 'electromagnetic', 'field', 'electromagnetic', 'induction', 'electromagnetic', 'radiation', 'Gaussian', 'surface', 'magnetic', 'field', 'magnetic', 'flux', 'magnetic', 'monopole', 'magnetic', 'permeability']
category_concepts_dict['physics'] = ["Newton's"]

category_concepts_dict['gr-qc'] = ['Special', 'relativity', 'general', 'relativity', 'Einstein', 'field', 'equationsCovariance', 'Einstein', 'manifold', 'equivalence', 'principle', 'four-momentum', 'four-vector', 'general', 'principle', 'of', 'relativity', 'geodesic', 'motion', 'gravity', 'gravitoelectromagnetism', 'inertial', 'frame', 'of', 'reference', 'invariance', 'length', 'contraction', 'Lorentzian', 'manifold', 'Lorentz', 'transformation', 'metric', 'Minkowski', 'diagram', 'Minkowski', 'space', 'principle', 'of', 'relativity', 'proper', 'length', 'proper', 'time', 'reference', 'frame', 'rest', 'energy', 'rest', 'mass', 'relativity', 'of', 'simultaneity', 'spacetime', 'special', 'principle', 'of', 'relativity', 'speed', 'of', 'light', 'stress–energy', 'tensor', 'time', 'dilation', 'twin', 'paradox', 'world', 'line']
#category_concepts_dict['gr-qc'] = ['relativity']

category_concepts_dict['quant-ph'] = ['Path', 'integral', 'formulation', 'scattering', 'theory', 'Schrödinger', 'equation', 'quantum', 'field', 'theory', 'quantum', 'statistical', 'mechanicsAdiabatic', 'approximation', 'correspondence', 'principle', 'free', 'particle', 'Hamiltonian', 'Hilbert', 'space', 'identical', 'particles', 'matrix', 'mechanics', "Planck's", 'constant', 'operators', 'quanta', 'quantization', 'quantum', 'entanglement', 'quantum', 'harmonic', 'oscillator', 'quantum', 'number', 'quantum', 'tunneling', "Schrödinger's", 'cat', 'Dirac', 'equation', 'spin', 'wavefunction', 'wave', 'mechanics', 'wave–particle', 'duality', 'zero-point', 'energy', 'Pauli', 'exclusion', 'principle', 'Heisenberg', 'uncertainty', 'principle']
#category_concepts_dict['quant-ph'] = ['wavefunction']

category_concepts_dict['hep-ph'] = ['Accelerator', 'physics', 'nuclear', 'physics', 'nuclear', 'astrophysics', 'particle', 'astrophysics', 'particle', 'physics', 'phenomenology', 'Standard', 'Model', 'quantum', 'field', 'theory', 'quantum', 'chromodynamics', 'electroweak', 'theory', 'effective', 'field', 'theory', 'lattice', 'field', 'theory', 'lattice', 'gauge', 'theory', 'gauge', 'theory', 'supersymmetry', 'Grand', 'Unified', 'Theory', 'superstring', 'theory', 'M-theory', 'Fundamental', 'force', '(gravitational', 'electromagnetic', 'weak', 'strong)', 'elementary', 'particle', 'spin', 'antimatter', 'spontaneous', 'symmetry', 'breaking', 'brane', 'string', 'quantum', 'gravity', 'theory', 'of', 'everything', 'vacuum', 'energy']
#category_concepts_dict['hep-ph'] = ['particle']

category_concepts_dict['cond-mat'] = ['Solid', 'state', 'physics', 'high', 'pressure', 'physics', 'low-temperature', 'physics', 'nanoscale', 'and', 'mesoscopic', 'physics', 'polymer', 'physics', 'BCS', 'theory', "Bloch's", 'theorem', 'Fermi', 'gas', 'Fermi', 'liquid', 'many-body', 'theory', 'Phases', '(gas', 'liquid', 'solid', 'Bose–Einstein', 'condensate', 'superconductor', 'superfluid)', 'electrical', 'conduction', 'magnetism', 'self-organization', 'spin', 'spontaneous', 'symmetry', 'breaking']
#category_concepts_dict['cond-mat'] = ['solid']

category_concepts_dict['astro-ph'] = ['Cosmology', 'gravitation', 'physics', 'high-energy', 'astrophysics', 'planetary', 'astrophysics', 'plasma', 'physics', 'space', 'physics', 'stellar', 'astrophysics', 'Big', 'Bang', 'Lambda-CDM', 'model', 'cosmic', 'inflation', 'general', 'relativity', 'law', 'of', 'universal', 'gravitation', 'Black', 'hole', 'cosmic', 'background', 'radiation', 'cosmic', 'string', 'cosmos', 'dark', 'energy', 'dark', 'matter', 'galaxy', 'gravity', 'gravitational', 'radiation', 'gravitational', 'singularity', 'planet', 'Solar', 'System', 'star', 'supernova', 'universe']
#category_concepts_dict['astro-ph'] = ['star']